// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://jqliogjaiahdbqumjmhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxbGlvZ2phaWFoZGJxdW1qbWh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDgxMzIsImV4cCI6MjA2NDUyNDEzMn0.qr6ZYGgxwvIW1RBw1UJvqTefmAm04Cw_UXUON_iSXU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
